---
title: "MaxHunter"
output: html_document
date: "2023-06-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(dplyr)
```
Read in the beta matrix via RDS
```{r}
setwd("/nfs/turbo/bakulski1/People/data/ffcw/methyl_data/Feb2022_datafreeze")
betaFileName <- "beta_analytic_freeze1.rds" # file.choose()
startrds <- Sys.time()
betas <- readRDS(betaFileName) # 5.9 GB
rdstime = Sys.time() - startrds; rdstime
# Time difference of 41.2518 secs
```
Implementation 2 functions
```{r}
# Assume input data is not all slope == 0
localMinMax <- function(fitted, zeroThreshold = 0.01) {
  # Testing: try different datasets
  # fitted <- density4Peak$y; zeroThreshold = 1/100 
  # fitted <- density4PeakInv$y; zeroThreshold = 1/100 
  fitted <- ifelse(fitted < zeroThreshold, 0, fitted)
  
  # Cases:
  # 1. If line increasing at start, plusMinus will be TRUE TRUE...
  # until we reach the first stationary point to the right
  
  # 2. If line decreasing/flat at start, plusMinus will be TRUE FALSE ... 
  # detect stationary point at index == 1
  # When slope is no longer zero, we will incorrectly detect a stationary point
  
  # this code cannot distinguish between negative slope and slope of zero
  plusMinus <- diff(c(-Inf, fitted)) > 0L
  
  # Find indices where the sign of the slope changes
  slopeZero <- cumsum(rle(plusMinus)$lengths); slopeZero
  
  if (length(slopeZero) == 1) {
    return(list("maximaIdx" = slopeZero, "minimaIdx" = c(1, 500)))
  }
  
  # browser()
  
  # 1. First slope sign change is a max
  # 2. First (artificial) slope sign change is a max and is located at index == 1
  # 3. First (artificial) slope sign change is just artificial. Second sign change is an inflection point
  whereMax <- seq.int(1L, length(slopeZero), 2L)
  # version 1
  # whereMin <- -whereMax
  
  # version 2: make these indices positive
  whereMin <- (1:length(slopeZero))[-whereMax] 
  
  # Case 3: Line starts out flat
  if (fitted[[1]] == fitted[[2]]) { 
    # Skip artificial first slope sign change (since we start from -Inf)
    whereMax <- whereMax[-1] 
    
    # Skip inflection point
    # version 1
    # whereMin <- c(-2, whereMin) 
    
    # version 2
    whereMin <- whereMin[-1]
    
    # Maybe not a good idea
    # slopeZero <- slopeZero[-2]
  }
  # # version 1
  # maxes <- slopeZero[whereMax]
  # mins <- slopeZero[whereMin]
  # 
  # return(list("maximaIdx" = maxes, "minimaIdx" = mins))
  
  # version 2
  # return(list("slopeZero" = slopeZero, "maximaIdx" = whereMax,
  # "minimaIdx" = whereMin))
  
  # version 3
  leftMin <- whereMax - 1
  if (leftMin[1] == 0) leftMin[1] = 1
  
  rightMin <- whereMax + 1
  if (rightMin[length(rightMin)] > length(slopeZero)) {
    rightMin[length(rightMin)] = length(slopeZero)
  } 
  
  data.frame("maximaIdx" = slopeZero[whereMax], "leftMinIdx" = slopeZero[leftMin], 
             "rightMinIdx" = slopeZero[rightMin])
}
```
Implementation 2 test data
```{r}
# Choose a weird distribution as test case
strangeIdx <- 261654 # 238564
testBetas <- betas[strangeIdx,]
testDensity <- density(testBetas, from = 0, to = 1, n = 500, 
                       bw = bw.SJ(betas[strangeIdx,]), adjust = 2)
# testBetas <- fourPeaksInv
# testDensity <- density4PeakInv
```
Run max/min detection and plot them on original distribution
```{r}
testminmax <- localMinMax(testDensity$y); testminmax

# # Plot maxima and minima/inflection points
# hist(betas[strangeIdx,], breaks = 500, xlim = c(0,1), probability = TRUE,
#      main = paste0("Histogram of betas of probe # ", strangeIdx, " (", rownames(betas)[strangeIdx], ")"),
#      xlab = "Beta",
#      ylab = "Probability density")
# lines(testDensity, col = "orchid", lwd = 2, pch = 19)
# points(testDensity$x[testminmax$maximaIdx], testDensity$y[testminmax$maximaIdx], col = "red", pch = 19, cex = 1.25)
# points(testDensity$x[testminmax$minimaIdx], testDensity$y[testminmax$minimaIdx], col = "blue", pch = 19, cex = 1.25)
```
Plot maxima and minima/inflection points
```{r}
# hist(testBetas, breaks = 500, xlim = c(0,1), probability = TRUE,
#      main = paste0("Histogram of betas of probe # ", strangeIdx, " (", rownames(betas)[strangeIdx], ")"),
#      xlab = "Beta",
#      ylab = "Probability density")

hist(testBetas, breaks = 500, xlim = c(0,1), probability = TRUE)
lines(testDensity, col = "orchid", lwd = 2, pch = 19)
points(testDensity$x[testminmax$maximaIdx], testDensity$y[testminmax$maximaIdx], col = "red", pch = 19, cex = 1.25)
points(testDensity$x[testminmax$leftMinIdx], testDensity$y[testminmax$leftMinIdx], col = "blue", pch = 19, cex = 1.25)
points(testDensity$x[testminmax$rightMinIdx], testDensity$y[testminmax$rightMinIdx], col = "blue", pch = 19, cex = 1.25)
```
Filtering based on size of peak
```{r}
#### ONLY DO THIS IF THERE IS MORE THAN ONE PEAK ####
if (length(testminmax$maximaIdx) > 1) {
  breaks = c(testminmax$leftMinIdx, testminmax$rightMinIdx[nrow(testminmax)])

  cutoff <- 0.01
  # Show peak sample size
  #aboveCutoff <- hist(testBetas, breaks = testDensity$x[breaks], freq = FALSE, plot = TRUE)$count/length(betas[strangeIdx,]) > cutoff
  # Skip plotting
  aboveCutoff <- hist(testBetas, breaks = testDensity$x[breaks], freq = FALSE, plot = TRUE)$count/length(testBetas) > cutoff
  aboveCutoff
  filtered <- testminmax[aboveCutoff,]
}
```
Plot detected peaks after filtering
```{r}
# hist(testBetas, breaks = 500, xlim = c(0,1), freq = FALSE, 
#      main = paste0("Histogram of betas of probe # ", strangeIdx, " (", rownames(betas)[strangeIdx], ")"),
#      xlab = "Beta",
#      ylab = "Probability density")

hist(testBetas, breaks = 500, xlim = c(0,1), freq = FALSE)
lines(testDensity, col = "orchid", lwd = 2, pch = 19)
points(testDensity$x[filtered$maximaIdx], testDensity$y[filtered$maximaIdx], col = "red", pch = 19, cex = 1.25)
points(testDensity$x[filtered$leftMinIdx], testDensity$y[filtered$leftMinIdx], col = "blue", pch = 19, cex = 1.25)
points(testDensity$x[filtered$rightMinIdx], testDensity$y[filtered$rightMinIdx], col = "blue", pch = 19, cex = 1.25)
```
Eliminate short peaks too close to other peaks
```{r}
#### ONLY DO THIS IF THERE IS ANY CROWDING ####
personalSpace <- 0.1
xValues <- testDensity$x[filtered$maximaIdx]
checkCrowding <- diff(xValues) < personalSpace

if (sum(checkCrowding) > 0) {
  finalPeaks <- filtered
  deactivate <- rep(FALSE, nrow(filtered))
  
  for (i in 1:nrow(finalPeaks)) {
    currentPeak <- finalPeaks$maximaIdx[i]
    if (deactivate[i]) next # Skip if already deactivated
    
    isNeighbor <- finalPeaks$maximaIdx != currentPeak &
                            xValues > testDensity$x[currentPeak] - personalSpace & 
                            xValues < testDensity$x[currentPeak] + personalSpace
    
    if (sum(isNeighbor) == 0) next # No neighbors found
    
    shorter <- testDensity$y[finalPeaks$maximaIdx] < testDensity$y[currentPeak]
    
    peaksToDeactivate <- which(isNeighbor & shorter)
    
    if (length(peaksToDeactivate) > 0) {
      suppressWarnings(deactivate[peaksToDeactivate] <- TRUE)
    }
  }
}
  
finalPeaks <- finalPeaks[!deactivate,]; finalPeaks
```
Plot after filtering crowded peaks
```{r}
  # hist(testBetas, breaks = 500, xlim = c(0,1), freq = FALSE, 
  #    main = paste0("Histogram of betas of probe # ", strangeIdx, " (", rownames(betas)[strangeIdx], ")"),
  #    xlab = "Beta",
  #    ylab = "Probability density")

hist(testBetas, breaks = 500, xlim = c(0,1), freq = FALSE)
  lines(testDensity, col = "orchid", lwd = 2, pch = 19)
  points(testDensity$x[finalPeaks$maximaIdx], testDensity$y[finalPeaks$maximaIdx], col = "red", pch = 19, cex = 1.25)


```

