---
title: "R Notebook"
output: html_notebook
---
Try GMMC
```{r}
library(mclust)
# library(mixtools)
totalRows <- nrow(betas)
gmmcResults <- data.table("optimalG" = numeric(totalRows), 
                          "groupNames" = vector(mode = "list", 
                                              length = totalRows),
                          "means" = vector(mode = "list", 
                                              length = totalRows),
                          "sigmasq" = vector(mode = "list", 
                                              length = totalRows),
                          "classification" = vector(mode = "list", 
                                              length = totalRows),
                          "G" = numeric(totalRows))
```

```{r}

# maxK <- 3
# bicThreshold <- 100
# mtResults <- numeric(10)
# myResults <- numeric(10)

startTime <- Sys.time()
# for (i in seq_along(betas)) {
#   print(i)
# Small-scale test
for (i in 1:5000) {
  fit <- Mclust(data = betas[i,], G = 1:3, modelNames = "E", verbose = F)
  
  # Sometimes the clusters are ridiculously small.
  keepCluster <- as.numeric(which(table(fit$classification)/ncol(betas) > proportionSample))
  
  gmmcResults[i,] <- list("optimalG" = length(keepCluster),
                          "groupNames" = keepCluster,
                          "means" = fit$parameters$mean[keepCluster],
                          "sigmasq" = fit$parameters$variance$sigmasq[keepCluster],
                          "classification" = fit$classification,
                          "G" = fit$G)
  
  # Small-scale test
  # hist(betas[i,], breaks = 500)
  # seeGMMC(data = betas[i,], groups = keepCluster, classification = fit$classification)

}
Sys.time() - startTime
# Small-scale test
# gmmcResults$optimalG[1:10]

# saveRDS(gmmcResults, file = "gmmcResults_1_5000.RDS")
```
See gmmcResult summary
```{r}
ggplot(data = gmmcResults, aes(optimalG)) +
  geom_bar() +
  geom_text(stat='count', aes(label=..count..), vjust = -1)
```
